### ISSUE TITLE
Incorrect ref in grid.rb::get_cursor_position

### ISSUE THREAD

**Issue by aks** [RubySource/opal_article#1]
Lines 67 & 68 have a bug:

```
      x = e[:clientX] + doc.scrollLeft + doc.documentElement.scrollLeft;
      y = e[:clientY] + doc.body.scrollTop + doc.documentElement.scrollTop;
```

A reference is made to `e` instead of `event`, which is the argument passed to the function.

The `x` coordinate references `doc.scrollLeft` while the `y` coordinate references `doc.body.scrollTop`.  Why is this?

**Comment by benjamintanweihao** [comment]
Thank you @aks!
